version: '3.8'
services:
  caddy:
    image: caddy:2-alpine
    ports:
      - "80:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./mywebsite:/usr/src/app/mywebsite
    depends_on:
      - web

  web:
    build: .
    volumes:
      - ./mywebsite:/usr/src/app/mywebsite
